### ISSUE TITLE
Website not accessible from Tor

### ISSUE THREAD

**Issue by achteo** [mojolicious/mojolicious.org#12]
Please make http://mojolicious.org usable for Tor users! This is just annoying and discriminating that Tor users must solve Google Captcha to access the site.

![Screenshot_2019-09-20_02-25-29](https://user-images.githubusercontent.com/55567983/65294378-eefc7d00-db4d-11e9-9b4d-6f66545134cf.png)

You can follow this guide https://github.com/allow-tor/on-cloudflare

**Comment by aaronrf** [comment]
I've just started using Tor too and discovered that it's not easy to access the docs.
It would be great if you could loosen the Cloudflare's filters. All popular MVC framework sites like Django, Rails, Laravel or ExpressJS are accessible from Tor without a need to solve the recaptcha, also metacpan is.

**Comment by jhthorsen** [comment]
Might be worth looking at these resources:

* https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing
* https://blog.cloudflare.com/the-trouble-with-tor/

**Comment by kraih** [comment]
I've relaxed the Cloudflare settings a bit too.
