### ISSUE TITLE
.mojo-perldoc container max-width shouldn't be 100%

### ISSUE THREAD

**Issue by smonff** [mojolicious/mojolicious.org#19]
By limiting the `max-width` of `.mojo-perldoc` to something like `768px` or `70%`, the readability of the documentation pages are improved. Reading such pages on a full width is almost impossible on large screens and should be artificially limited. The `${limit}` should be debated but I think a `[70-75]%` range is reasonable.

Code zones are not a problem since they are mostly always short. Prose zones are more problematic and difficult to read on large screens. They should be artificially limited for larger screens, responsiveness doesn't mean there shouldn't be limits.

After 
![image](https://user-images.githubusercontent.com/1219097/95916538-181b2b80-0da9-11eb-8881-9a56f9b0fbf9.png)
   
Before
![image](https://user-images.githubusercontent.com/1219097/95916720-65979880-0da9-11eb-9a47-4ae2baf6ed6b.png)

**Comment by kraih** [comment]
Maybe, i don't know.
