### ISSUE TITLE
Can't link to entries in perlfunc

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojolicious.org#7]
Unlike MetaCPAN we [can't link](https://mojolicious.org/perldoc/perlfunc) directly to functions in [perlfunc](https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#split-/PATTERN/,EXPR,LIMIT).

**Comment by dotandimet** [comment]
Looks like [you can](https://mojolicious.org/perldoc/perlfunc#split-PATTERN-EXPR-LIMIT) - I think you fixed this [here](https://github.com/mojolicious/mojolicious.org/commit/d936abeffad93ea06c736c22b027ff1edd5a6994)
